# Generated by Django 4.0 on 2023-11-29 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usertypes', '0003_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='url',
        ),
    ]
