# Generated by Django 4.0 on 2023-11-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertypes', '0004_remove_blog_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
